services:
  mailqueue:
    build: .
    volumes:
      - /home/user/maildir:/maildir
      - faildir:/faildir
    environment:
      - SERVER=smtp.example.com
      - PORT=465
      - USERNAME=mailqueue@example.com
      - PASSWORD=very_secure_password
      - SENDER=mailqueue@example.com
volumes:
  faildir:
