services:
  mailqueue:
    container_name: mailqueue
    user: "120:120"
    image: jwooning/mailqueue
    pull_policy: build
    build: .
    restart: always
    volumes:
      - /home/user/maildir:/maildir
      - faildir:/faildir
    environment:
      - UMASK=002
      - SERVER=smtp.example.com
      - PORT=465
      - USERNAME=mailqueue@example.com
      - PASSWORD=very_secure_password
      - SENDER=mailqueue@example.com
volumes:
  faildir:
